apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-quickack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-quickack
  template:
    metadata:
      labels:
        app: test-quickack
    spec:
      initContainers:
      - name: init-setquickack
        image: docker.io/a9d593e2/mariner2.0-quickack:003
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - image: mcr.microsoft.com/cbl-mariner/base/core:2.0
        name: application
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
        command:
        - sleep
        - inf