FROM mcr.microsoft.com/cbl-mariner/base/core:2.0 AS iproute
LABEL org.opencontainers.image.authors="ioan corcodel"
LABEL "Purpose"="set quickack using initContainer on default route"
RUN tdnf install -y iproute

FROM iproute AS quickack
RUN chmod u+s /usr/sbin/ip
CMD ["/bin/sh", "-c", "ip route change `ip route | grep default | sed 's/.*/&quickack 1/g'` ; ip route show"]