# 'nft add chain filter' is failing on Azure Linux!
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  labels:
    app: packet-trace
  name: packet-trace
spec:
  selector:
    matchLabels:
      app: packet-trace
  template:
    metadata:
      labels:
        app: packet-trace
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: mcr.microsoft.com/mirror/docker/library/busybox:1.35 
        env:
        - name: LB
          # Loadbalancer service IP
          value: "10.10.10.11"
        - name: TIMEOUT
          # Timeout in seconds to stop tracing automatically
          value: "180"
        - name: CLIENT
          # Client IP sending cURL request"
          value: "10.10.1.11" 
        command:
        - /bin/sh
        - -xc
        - nsenter --mount=/proc/1/ns/mnt -- bash -xc "timeout $TIMEOUT tcpdump -tttt -i any -nnlSv host $LB ; nft add chain filter trace_chain { type filter hook prerouting priority -301\; } ; nft add rule filter trace_chain meta nftrace set 1 ; timeout $TIMEOUT nft monitor trace | grep $LB ; nft delete chain filter trace_chain ; sleep inf"
        name: packet-trace
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
      hostPID: true
      hostNetwork: true