apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: pingpong-thresh
spec:
  selector:
    matchLabels:
      app: pingpong-thresh
  template:
    metadata:
      labels:
        app: pingpong-thresh
    spec:
     nodeSelector:
      agentpool: aks-nodepool1-32891235-vmss000004
     containers:
     - name: pingpong-thresh
       command:
       - /bin/bash
       - -xc
       - tdnf install util-linux procps -y ; nsenter --mount=/proc/1/ns/mnt -- bash -xc "sysctl net.core.tcp_pingpong_thresh ; sysctl -w net.core.tcp_pingpong_thresh=3 ; sysctl net.core.tcp_pingpong_thresh; sleep inf"
      #  - nsenter
      #  - --mount=/proc/1/ns/mnt
      #  - --
      #  - bash
      #  - -xc
      #  - |
      #    sysctl net.core.tcp_pingpong_thresh
      #    sysctl -w net.core.tcp_pingpong_thresh=3
      #    sysctl net.core.tcp_pingpong_thresh
      #    sleep infinity
       image: mcr.microsoft.com/azurelinux/base/core:3.0
       resources:
         requests:
           cpu: 50m
           memory: 50M
       securityContext:
         privileged: true
